//! Egress connectivity tests - verifies VMs can reach the host network
//!
//! Tests both fresh VMs and cloned VMs for:
//! - HTTP connectivity from VM to a local test server on the host
//! - HTTP connectivity from container to the same test server
//!
//! Uses a pure Rust LocalTestServer bound on the host - no external network dependencies.
//! Both bridged and rootless networking modes are tested.

#![cfg(feature = "integration-slow")]

mod common;

use anyhow::{Context, Result};
use std::time::Duration;

/// Test egress connectivity for fresh VM with bridged networking
#[cfg(feature = "privileged-tests")]
#[tokio::test]
async fn test_egress_fresh_bridged() -> Result<()> {
    egress_fresh_test_impl("bridged").await
}

/// Test egress connectivity for fresh VM with rootless networking
#[tokio::test]
async fn test_egress_fresh_rootless() -> Result<()> {
    egress_fresh_test_impl("rootless").await
}

/// Test egress connectivity for cloned VM with bridged networking
#[cfg(feature = "privileged-tests")]
#[tokio::test]
async fn test_egress_clone_bridged() -> Result<()> {
    egress_clone_test_impl("bridged").await
}

/// Test egress connectivity for cloned VM with rootless networking
#[tokio::test]
async fn test_egress_clone_rootless() -> Result<()> {
    egress_clone_test_impl("rootless").await
}

/// Test egress connectivity for fresh VM with routed networking
#[cfg(feature = "privileged-tests")]
#[tokio::test]
async fn test_egress_fresh_routed() -> Result<()> {
    egress_fresh_test_impl("routed").await
}

/// Test egress connectivity for cloned VM with routed networking
#[cfg(feature = "privileged-tests")]
#[tokio::test]
async fn test_egress_clone_routed() -> Result<()> {
    egress_clone_test_impl("routed").await
}

/// A restored routed clone must be able to egress the instant it is up.
///
/// Routed guest traffic leaves through the namespace's IPv6 default-route nexthop:
/// the host veth's link-local. IPv6 Duplicate Address Detection used to make that
/// address — and the namespace's own br0 link-local, which has to source the
/// Neighbor Solicitation that resolves it — `tentative` for
/// rand(0..router_solicitation_delay=1s) + dad_transmits(1) x retrans_time_ms(1000).
/// A tentative address neither answers nor can source an NS, so every restored
/// routed clone had NO egress for 1-2s after its veth came up. Cold boots hid it
/// (DAD ran in the shadow of the multi-second guest boot); clones are ready in
/// ~700ms, so it landed on the critical path — measured p50 1,081ms to first
/// connection versus 3ms for every other egress mode.
///
/// The `nodad` assertion (anchored to the exact EUI-64 address fcvm installs) is
/// the deterministic catcher: a kernel-autogenerated link-local never carries that
/// flag, so a regression fails this test every run rather than only when the random
/// DAD delay happens to be long. There is deliberately NO timing assertion: by the
/// time the harness can exec into the clone (health poll + state lookups, ~0.5-1s
/// after the veth came up) the DAD window has already expired, so any wall-clock
/// bound measured from here would pass with the bug present. The in-guest probe at
/// the end is a functional egress check only.
#[cfg(feature = "privileged-tests")]
#[tokio::test]
async fn test_egress_clone_routed_no_dad_stall() -> Result<()> {
    let (baseline_name, clone_name, snapshot_name, _) = common::unique_names("egress-routed-dad");

    println!("\n╔═══════════════════════════════════════════════════════════════╗");
    println!("║     Routed Clone: no DAD stall on restore                     ║");
    println!("╚═══════════════════════════════════════════════════════════════╝\n");

    let test_server = common::LocalTestServer::start_on_available_port("::")
        .await
        .context("starting local test server")?;
    let host_ipv6 = common::get_host_ipv6().await?;
    let port = test_server.port;
    println!("  Host test server: [{}]:{}", host_ipv6, port);

    println!("\nStep 1: Starting baseline VM '{}'...", baseline_name);
    let (_baseline_child, baseline_pid) = common::spawn_fcvm_with_logs(
        &[
            "podman",
            "run",
            "--name",
            &baseline_name,
            "--network",
            "routed",
            common::TEST_IMAGE,
        ],
        &baseline_name,
    )
    .await
    .context("spawning baseline VM")?;
    if let Err(e) = common::poll_health_by_pid(baseline_pid, 300).await {
        test_server.stop().await;
        common::kill_process(baseline_pid).await;
        return Err(e.context("baseline VM failed to become healthy"));
    }
    println!("  ✓ Baseline VM healthy");

    println!("\nStep 2: Creating snapshot '{}'...", snapshot_name);
    let snap = tokio::process::Command::new(common::find_fcvm_binary()?)
        .args([
            "snapshot",
            "create",
            "--pid",
            &baseline_pid.to_string(),
            "--tag",
            &snapshot_name,
        ])
        .output()
        .await
        .context("running snapshot create")?;
    if !snap.status.success() {
        test_server.stop().await;
        common::kill_process(baseline_pid).await;
        anyhow::bail!(
            "snapshot creation failed: {}",
            String::from_utf8_lossy(&snap.stderr)
        );
    }
    common::kill_process(baseline_pid).await;
    println!("  ✓ Snapshot created, baseline killed");

    println!("\nStep 3: Starting memory server...");
    let (_serve_child, serve_pid) =
        common::spawn_fcvm_with_logs(&["snapshot", "serve", &snapshot_name], "uffd-server-dad")
            .await
            .context("spawning memory server")?;
    common::poll_serve_state_by_pid(serve_pid, 30).await?;
    println!("  ✓ Memory server ready (PID: {})", serve_pid);

    println!("\nStep 4: Spawning clone '{}'...", clone_name);
    let (_clone_child, clone_pid) = common::spawn_fcvm_with_logs(
        &[
            "snapshot",
            "run",
            "--pid",
            &serve_pid.to_string(),
            "--name",
            &clone_name,
        ],
        &clone_name,
    )
    .await
    .context("spawning clone")?;
    common::poll_health_by_pid(clone_pid, 120).await?;
    println!("  ✓ Clone is healthy");

    let result = assert_routed_clone_nexthop_nodad_and_egress(clone_pid, &host_ipv6, port).await;

    println!("\nCleaning up...");
    common::kill_process(clone_pid).await;
    common::kill_process(serve_pid).await;
    test_server.stop().await;

    result?;
    println!("\n✅ ROUTED CLONE HAS NO DAD STALL");
    Ok(())
}

/// Assert the clone's IPv6 nexthop is exactly the nodad address fcvm installs, and
/// that the guest has working egress.
///
/// The nodad/tentative checks are anchored to the EUI-64 link-local computed from
/// the veth's MAC — the address fcvm installs and the namespace's default route
/// points at — so an autogenerated address (EUI-64 without nodad, or stable-privacy
/// at some other address) can never satisfy them.
#[cfg(feature = "privileged-tests")]
async fn assert_routed_clone_nexthop_nodad_and_egress(
    clone_pid: u32,
    host_ipv6: &str,
    port: u16,
) -> Result<()> {
    let host_veth = common::get_network_field(clone_pid, "host_veth")
        .await
        .context("routed clone recorded no host_veth")?;
    let namespace = common::get_network_field(clone_pid, "namespace_name")
        .await
        .context("routed clone recorded no namespace_name")?;
    println!("  clone host_veth={} namespace={}", host_veth, namespace);

    // 1. The nexthop address — the EUI-64 link-local the namespace's default route
    //    points at — must exist, carry the `nodad` flag (only fcvm's explicit add
    //    sets it; the kernel never autogenerates with it), and not be tentative.
    let expected_ll = eui64_link_local(&host_veth).await?;
    let addr = tokio::process::Command::new("ip")
        .args(["-6", "addr", "show", "dev", &host_veth, "scope", "link"])
        .output()
        .await
        .context("reading host veth link-local")?;
    let addr = String::from_utf8_lossy(&addr.stdout);
    let ll_line = addr
        .lines()
        .find(|line| {
            line.trim_start()
                .strip_prefix("inet6 ")
                .and_then(|rest| rest.split('/').next())
                .and_then(|a| a.parse::<std::net::Ipv6Addr>().ok())
                == Some(expected_ll)
        })
        .with_context(|| {
            format!(
                "host veth {} does not hold {} — the guest's IPv6 nexthop does not exist:\n{}",
                host_veth, expected_ll, addr
            )
        })?;
    assert!(
        ll_line.contains("nodad"),
        "host veth {} link-local {} lacks the nodad flag, so the kernel autogenerated \
         it and ran DAD on it — the guest's IPv6 nexthop is unusable for 1-2s:\n{}",
        host_veth,
        expected_ll,
        addr
    );
    assert!(
        !ll_line.contains("tentative"),
        "host veth {} link-local {} is still tentative — it cannot answer Neighbor \
         Solicitations, so the guest has no egress:\n{}",
        host_veth,
        expected_ll,
        addr
    );
    println!(
        "  ✓ nexthop {} is present, nodad, and not tentative",
        expected_ll
    );

    // 2. Nothing inside the namespace may be tentative either: br0's link-local is
    //    the source address for the NS that resolves the nexthop.
    let ns_addr = tokio::process::Command::new("ip")
        .args(["netns", "exec", &namespace, "ip", "-6", "addr", "show"])
        .output()
        .await
        .context("reading namespace IPv6 addresses")?;
    let ns_addr = String::from_utf8_lossy(&ns_addr.stdout);
    assert!(
        !ns_addr.contains("tentative"),
        "namespace {} still has tentative IPv6 addresses, so it cannot source a \
         Neighbor Solicitation for the nexthop:\n{}",
        namespace,
        ns_addr
    );
    println!("  ✓ no tentative addresses in the clone namespace");

    // 3. End-to-end: the guest must reach the host over the routed path. This is a
    //    functional egress check, NOT a DAD-stall catcher — by the time `fcvm exec`
    //    can run, any DAD window has long expired, so no wall-clock bound measured
    //    from here could catch the stall (assertion 1 above is the catcher). Each
    //    attempt is capped at 50ms by `timeout`: bash's /dev/tcp has no connect
    //    timeout of its own, so a black-holed SYN would otherwise block for the
    //    kernel's full ~130s retry sequence and this test would hang instead of
    //    failing.
    let script = format!(
        r#"deadline=$((SECONDS+15))
while :; do
  if timeout 0.05 bash -c "exec 3<>/dev/tcp/{host}/{port}" 2>/dev/null; then echo NETRDY_OK; exit 0; fi
  if [ "$SECONDS" -ge "$deadline" ]; then echo NETRDY_FAIL; exit 1; fi
done"#,
        host = host_ipv6,
        port = port
    );
    let probe = tokio::process::Command::new(common::find_fcvm_binary()?)
        .args([
            "exec",
            "--pid",
            &clone_pid.to_string(),
            "--vm",
            "--",
            "bash",
            "-c",
            &script,
        ])
        .output()
        .await
        .context("running in-guest connect probe")?;
    let out = String::from_utf8_lossy(&probe.stdout);
    assert!(
        out.lines().any(|l| l.trim() == "NETRDY_OK"),
        "guest could not reach [{}]:{} over routed IPv6 within 15s \
         (stdout={:?}, stderr={:?})",
        host_ipv6,
        port,
        out.trim(),
        String::from_utf8_lossy(&probe.stderr).trim()
    );
    println!("  ✓ guest egress works");
    Ok(())
}

/// Compute the EUI-64 link-local for an interface from its MAC, independently of
/// fcvm's own computation, so the nexthop assertion cross-checks fcvm's result.
#[cfg(feature = "privileged-tests")]
async fn eui64_link_local(iface: &str) -> Result<std::net::Ipv6Addr> {
    let out = tokio::process::Command::new("ip")
        .args(["-j", "link", "show", "dev", iface])
        .output()
        .await
        .context("running `ip -j link show`")?;
    anyhow::ensure!(
        out.status.success(),
        "`ip -j link show dev {}` failed: {}",
        iface,
        String::from_utf8_lossy(&out.stderr).trim()
    );
    let links: Vec<serde_json::Value> =
        serde_json::from_slice(&out.stdout).context("parsing `ip -j link show` JSON")?;
    let mac = links
        .first()
        .and_then(|l| l.get("address"))
        .and_then(|a| a.as_str())
        .with_context(|| format!("no MAC address for {}", iface))?;
    let bytes = mac
        .split(':')
        .map(|h| u8::from_str_radix(h, 16))
        .collect::<Result<Vec<u8>, _>>()
        .with_context(|| format!("unparseable MAC {:?} on {}", mac, iface))?;
    anyhow::ensure!(
        bytes.len() == 6,
        "MAC {:?} on {} is not 6 octets",
        mac,
        iface
    );
    // EUI-64: flip the universal/local bit of the first octet, insert ff:fe.
    format!(
        "fe80::{:02x}{:02x}:{:02x}ff:fe{:02x}:{:02x}{:02x}",
        bytes[0] ^ 0x02,
        bytes[1],
        bytes[2],
        bytes[3],
        bytes[4],
        bytes[5]
    )
    .parse()
    .context("parsing computed EUI-64 link-local")
}

/// Calculate the URL a VM should use to reach a test server on the host
async fn get_egress_url(network: &str, port: u16) -> Result<String> {
    match network {
        "rootless" => {
            // For rootless, pasta gateway is 10.0.2.2
            Ok(format!("http://10.0.2.2:{}/", port))
        }
        "bridged" => {
            // For bridged, use host's primary IPv4 (reachable via CONNMARK routing)
            let host_ip = common::get_host_primary_ip().await?;
            Ok(format!("http://{}:{}/", host_ip, port))
        }
        "routed" => {
            // For routed, use host's IPv6. Each clone has a unique IPv6,
            // so return routing works naturally (no CONNMARK needed).
            let host_ipv6 = common::get_host_ipv6().await?;
            Ok(format!("http://[{}]:{}/", host_ipv6, port))
        }
        _ => anyhow::bail!("Unknown network type: {}", network),
    }
}

/// Implementation for testing egress on a fresh (non-cloned) VM
async fn egress_fresh_test_impl(network: &str) -> Result<()> {
    let (vm_name, _, _, _) = common::unique_names(&format!("egress-fresh-{}", network));

    println!("\n╔═══════════════════════════════════════════════════════════════╗");
    println!(
        "║     Fresh VM Egress Test ({:8})                          ║",
        network
    );
    println!("╚═══════════════════════════════════════════════════════════════╝\n");

    // Start local test server on host
    // Routed uses IPv6, so bind on :: (dual-stack). Bridged uses IPv4 on all interfaces.
    let bind_addr = match network {
        "rootless" => "127.0.0.1",
        "routed" => "::",
        _ => "0.0.0.0",
    };

    let test_server = common::LocalTestServer::start_on_available_port(bind_addr)
        .await
        .context("starting local test server")?;

    let egress_url = get_egress_url(network, test_server.port).await?;
    println!(
        "  Local test server: {} (VM will connect to {})",
        test_server.url, egress_url
    );

    let fcvm_path = common::find_fcvm_binary()?;

    // Step 1: Start VM
    println!("\nStep 1: Starting fresh VM '{}'...", vm_name);
    let (_child, vm_pid) = common::spawn_fcvm_with_logs(
        &[
            "podman",
            "run",
            "--name",
            &vm_name,
            "--network",
            network,
            common::TEST_IMAGE,
        ],
        &vm_name,
    )
    .await
    .context("spawning VM")?;

    println!("  Waiting for VM to become healthy (PID: {})...", vm_pid);
    if let Err(e) = common::poll_health_by_pid(vm_pid, 180).await {
        test_server.stop().await;
        common::kill_process(vm_pid).await;
        return Err(e.context("VM failed to become healthy"));
    }
    println!("  ✓ VM healthy");

    // Step 2: Test egress
    println!("\nStep 2: Testing egress connectivity to local server...");
    let egress_result = test_egress(&fcvm_path, vm_pid, &egress_url).await;

    // Cleanup
    println!("\nCleaning up...");
    test_server.stop().await;
    common::kill_process(vm_pid).await;
    println!("  Killed VM and test server");

    // Report result
    match egress_result {
        Ok(()) => {
            println!("\n✅ FRESH VM EGRESS TEST PASSED! (network: {})", network);
            Ok(())
        }
        Err(e) => {
            println!("\n❌ FRESH VM EGRESS TEST FAILED!");
            println!("  Error: {}", e);
            Err(e)
        }
    }
}

/// Implementation for testing egress on a cloned VM
async fn egress_clone_test_impl(network: &str) -> Result<()> {
    let (baseline_name, clone_name, snapshot_name, _) =
        common::unique_names(&format!("egress-{}", network));

    println!("\n╔═══════════════════════════════════════════════════════════════╗");
    println!(
        "║     Cloned VM Egress Test ({:8})                         ║",
        network
    );
    println!("╚═══════════════════════════════════════════════════════════════╝\n");

    // Start local test server on host
    // Routed uses IPv6, so bind on :: (dual-stack). Bridged uses IPv4 on all interfaces.
    let bind_addr = match network {
        "rootless" => "127.0.0.1",
        "routed" => "::",
        _ => "0.0.0.0",
    };

    let test_server = common::LocalTestServer::start_on_available_port(bind_addr)
        .await
        .context("starting local test server")?;

    let egress_url = get_egress_url(network, test_server.port).await?;
    println!(
        "  Local test server: {} (VM will connect to {})",
        test_server.url, egress_url
    );

    let fcvm_path = common::find_fcvm_binary()?;

    // Step 1: Start baseline VM
    println!("\nStep 1: Starting baseline VM '{}'...", baseline_name);
    let (_baseline_child, baseline_pid) = common::spawn_fcvm_with_logs(
        &[
            "podman",
            "run",
            "--name",
            &baseline_name,
            "--network",
            network,
            common::TEST_IMAGE,
        ],
        &baseline_name,
    )
    .await
    .context("spawning baseline VM")?;

    println!(
        "  Waiting for baseline VM to become healthy (PID: {})...",
        baseline_pid
    );
    // Use 300 second timeout to account for rootfs creation on first run
    if let Err(e) = common::poll_health_by_pid(baseline_pid, 300).await {
        test_server.stop().await;
        common::kill_process(baseline_pid).await;
        return Err(e.context("baseline VM failed to become healthy"));
    }
    println!("  ✓ Baseline VM healthy");

    // Test egress on baseline first
    println!("\n  Testing baseline egress to local server...");
    if let Err(e) = test_egress(&fcvm_path, baseline_pid, &egress_url).await {
        test_server.stop().await;
        common::kill_process(baseline_pid).await;
        return Err(anyhow::anyhow!("Baseline egress failed: {}", e));
    }
    println!("  ✓ Baseline VM egress works");

    // Step 2: Create snapshot
    println!("\nStep 2: Creating snapshot '{}'...", snapshot_name);
    let output = tokio::process::Command::new(&fcvm_path)
        .args([
            "snapshot",
            "create",
            "--pid",
            &baseline_pid.to_string(),
            "--tag",
            &snapshot_name,
        ])
        .output()
        .await
        .context("running snapshot create")?;

    if !output.status.success() {
        test_server.stop().await;
        common::kill_process(baseline_pid).await;
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("Snapshot creation failed: {}", stderr);
    }
    println!("  ✓ Snapshot created");

    // Kill baseline - we only need the snapshot
    common::kill_process(baseline_pid).await;
    println!("  Killed baseline VM");
    tokio::time::sleep(Duration::from_secs(1)).await;

    // Step 3: Start memory server
    println!("\nStep 3: Starting memory server...");
    let (_serve_child, serve_pid) =
        common::spawn_fcvm_with_logs(&["snapshot", "serve", &snapshot_name], "uffd-server")
            .await
            .context("spawning memory server")?;

    // Wait for serve process to save its state file
    common::poll_serve_state_by_pid(serve_pid, 30).await?;
    println!("  ✓ Memory server ready (PID: {})", serve_pid);

    // Step 4: Spawn clone
    println!("\nStep 4: Spawning clone '{}'...", clone_name);
    let serve_pid_str = serve_pid.to_string();
    let (_clone_child, clone_pid) = common::spawn_fcvm_with_logs(
        &[
            "snapshot",
            "run",
            "--pid",
            &serve_pid_str,
            "--name",
            &clone_name,
        ],
        &clone_name,
    )
    .await
    .context("spawning clone")?;

    println!(
        "  Waiting for clone to become healthy (PID: {})...",
        clone_pid
    );
    common::poll_health_by_pid(clone_pid, 120).await?;
    println!("  ✓ Clone is healthy");

    // Step 5: Test egress on clone
    println!("\nStep 5: Testing clone egress connectivity to local server...");
    let clone_egress = test_egress(&fcvm_path, clone_pid, &egress_url).await;

    // Cleanup
    println!("\nCleaning up...");
    common::kill_process(clone_pid).await;
    println!("  Killed clone");
    common::kill_process(serve_pid).await;
    println!("  Killed memory server");
    test_server.stop().await;
    println!("  Stopped test server");

    // Report result
    match clone_egress {
        Ok(()) => {
            println!("\n✅ CLONED VM EGRESS TEST PASSED! (network: {})", network);
            Ok(())
        }
        Err(e) => {
            println!("\n❌ CLONED VM EGRESS TEST FAILED!");
            println!("  Error: {}", e);
            Err(e)
        }
    }
}

/// Test egress connectivity from both VM and container level
async fn test_egress(fcvm_path: &std::path::Path, pid: u32, egress_url: &str) -> Result<()> {
    // Test 1: VM-level egress using curl (available in Ubuntu guest)
    println!("  Testing VM-level egress (curl to {})...", egress_url);
    let vm_output = tokio::process::Command::new(fcvm_path)
        .args([
            "exec",
            "--pid",
            &pid.to_string(),
            "--vm",
            "--",
            "curl",
            "-s",
            "--noproxy",
            "*",
            "--max-time",
            "5",
            egress_url,
        ])
        .output()
        .await
        .context("running curl in VM")?;

    if !vm_output.status.success() {
        let stderr = String::from_utf8_lossy(&vm_output.stderr);
        anyhow::bail!(
            "VM egress failed: exit={}, stderr='{}'",
            vm_output.status,
            stderr.trim()
        );
    }

    let response = String::from_utf8_lossy(&vm_output.stdout);
    if !response.contains("TEST_SUCCESS") {
        anyhow::bail!("VM egress got unexpected response: {}", response.trim());
    }
    println!("    ✓ VM egress succeeded (got TEST_SUCCESS)");

    // Test 2: Container-level egress using wget (available in nginx:alpine)
    println!(
        "  Testing container-level egress (wget to {})...",
        egress_url
    );

    let container_output = tokio::process::Command::new(fcvm_path)
        .args([
            "exec",
            "--pid",
            &pid.to_string(),
            "--",
            "wget",
            "-q",
            "-O",
            "-",
            "-Y",
            "off",
            "--timeout=10",
            egress_url,
        ])
        .output()
        .await
        .context("running wget in container")?;

    if !container_output.status.success() {
        let stderr = String::from_utf8_lossy(&container_output.stderr);
        anyhow::bail!(
            "Container egress failed: exit={}, stderr='{}'",
            container_output.status,
            stderr.trim()
        );
    }

    let response = String::from_utf8_lossy(&container_output.stdout);
    if !response.contains("TEST_SUCCESS") {
        anyhow::bail!(
            "Container egress got unexpected response: {}",
            response.trim()
        );
    }
    println!("    ✓ Container egress succeeded (got TEST_SUCCESS)");

    Ok(())
}
